import 'package:my_business/demo/measure.dart';

class Convert {
  int id;
  int userId;
  String name;
  Measure firstName;
  double firstValue;
  Measure secondtName;
  double secondValue;
  Convert({
    required this.id,
    required this.userId,
    required this.name,
    required this.firstName,
    required this.firstValue,
    required this.secondtName,
    required this.secondValue,
  });
}

class ConvertDb {
  List<Convert> getConvert() {
    return [
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "name",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "na7867me",
          firstName: Measure(id: 1, userId: 1, name: "name7867"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "nam67867e2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "n866ame",
          firstName: Measure(id: 1, userId: 1, name: "n787ame"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "nam78e2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "nyu67ame",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "nawefrgtme",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
      Convert(
          id: 1,
          userId: 1,
          name: "nawqeqwme",
          firstName: Measure(id: 1, userId: 1, name: "name"),
          firstValue: 50,
          secondtName: Measure(id: 1, userId: 1, name: "name2"),
          secondValue: 10),
     
    ];
  }
}
