class Customer {
  int id;
  int userId;
  String name;
  String phone;
  Customer({
    required this.id,
    required this.userId,
    required this.name,
    required this.phone,
  });
}

class CustomerDb {
  List<Customer> getCustomer() {
    return [
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name1", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name2", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name3", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name4", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name5", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name6", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name7", phone: "phone"),
      Customer(id: 1, userId: 1, name: "name8", phone: "phone"),
    ];
  }
}
